// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: inboxapi/app_versions.proto

package inboxapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppVersions_GetVersionsDetails_FullMethodName = "/inboxapi.AppVersions/GetVersionsDetails"
)

// AppVersionsClient is the client API for AppVersions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppVersionsClient interface {
	// GetVersionsDetails returns app versions order by semver desc with markdown texts
	GetVersionsDetails(ctx context.Context, in *GetVersionsDetailsRequest, opts ...grpc.CallOption) (*GetVersionsDetailsResponse, error)
}

type appVersionsClient struct {
	cc grpc.ClientConnInterface
}

func NewAppVersionsClient(cc grpc.ClientConnInterface) AppVersionsClient {
	return &appVersionsClient{cc}
}

func (c *appVersionsClient) GetVersionsDetails(ctx context.Context, in *GetVersionsDetailsRequest, opts ...grpc.CallOption) (*GetVersionsDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionsDetailsResponse)
	err := c.cc.Invoke(ctx, AppVersions_GetVersionsDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppVersionsServer is the server API for AppVersions service.
// All implementations must embed UnimplementedAppVersionsServer
// for forward compatibility.
type AppVersionsServer interface {
	// GetVersionsDetails returns app versions order by semver desc with markdown texts
	GetVersionsDetails(context.Context, *GetVersionsDetailsRequest) (*GetVersionsDetailsResponse, error)
	mustEmbedUnimplementedAppVersionsServer()
}

// UnimplementedAppVersionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppVersionsServer struct{}

func (UnimplementedAppVersionsServer) GetVersionsDetails(context.Context, *GetVersionsDetailsRequest) (*GetVersionsDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersionsDetails not implemented")
}
func (UnimplementedAppVersionsServer) mustEmbedUnimplementedAppVersionsServer() {}
func (UnimplementedAppVersionsServer) testEmbeddedByValue()                     {}

// UnsafeAppVersionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppVersionsServer will
// result in compilation errors.
type UnsafeAppVersionsServer interface {
	mustEmbedUnimplementedAppVersionsServer()
}

func RegisterAppVersionsServer(s grpc.ServiceRegistrar, srv AppVersionsServer) {
	// If the following call pancis, it indicates UnimplementedAppVersionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppVersions_ServiceDesc, srv)
}

func _AppVersions_GetVersionsDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionsDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppVersionsServer).GetVersionsDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppVersions_GetVersionsDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppVersionsServer).GetVersionsDetails(ctx, req.(*GetVersionsDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppVersions_ServiceDesc is the grpc.ServiceDesc for AppVersions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppVersions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inboxapi.AppVersions",
	HandlerType: (*AppVersionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersionsDetails",
			Handler:    _AppVersions_GetVersionsDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inboxapi/app_versions.proto",
}
