// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: inboxapi/proposal.proto

package inboxapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFeaturedProposalsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProposalIds []string `protobuf:"bytes,1,rep,name=proposal_ids,json=proposalIds,proto3" json:"proposal_ids,omitempty"`
}

func (x *GetFeaturedProposalsResponse) Reset() {
	*x = GetFeaturedProposalsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFeaturedProposalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeaturedProposalsResponse) ProtoMessage() {}

func (x *GetFeaturedProposalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeaturedProposalsResponse.ProtoReflect.Descriptor instead.
func (*GetFeaturedProposalsResponse) Descriptor() ([]byte, []int) {
	return file_inboxapi_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeaturedProposalsResponse) GetProposalIds() []string {
	if x != nil {
		return x.ProposalIds
	}
	return nil
}

type GetAISummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProposalId string `protobuf:"bytes,2,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (x *GetAISummaryRequest) Reset() {
	*x = GetAISummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_proposal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAISummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAISummaryRequest) ProtoMessage() {}

func (x *GetAISummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_proposal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAISummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAISummaryRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *GetAISummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAISummaryRequest) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

type GetAISummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
}

func (x *GetAISummaryResponse) Reset() {
	*x = GetAISummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_proposal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAISummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAISummaryResponse) ProtoMessage() {}

func (x *GetAISummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_proposal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAISummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAISummaryResponse) Descriptor() ([]byte, []int) {
	return file_inboxapi_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *GetAISummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_inboxapi_proposal_proto protoreflect.FileDescriptor

var file_inboxapi_proposal_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x6e, 0x62, 0x6f, 0x78,
	0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x41, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x64, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x49, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x49, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x49, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x32, 0xb1, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x12, 0x56, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x26, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x41, 0x49, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1d, 0x2e, 0x69, 0x6e,
	0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x69, 0x6e, 0x62,
	0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x49, 0x53, 0x75, 0x6d, 0x6d, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b,
	0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inboxapi_proposal_proto_rawDescOnce sync.Once
	file_inboxapi_proposal_proto_rawDescData = file_inboxapi_proposal_proto_rawDesc
)

func file_inboxapi_proposal_proto_rawDescGZIP() []byte {
	file_inboxapi_proposal_proto_rawDescOnce.Do(func() {
		file_inboxapi_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_inboxapi_proposal_proto_rawDescData)
	})
	return file_inboxapi_proposal_proto_rawDescData
}

var file_inboxapi_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inboxapi_proposal_proto_goTypes = []any{
	(*GetFeaturedProposalsResponse)(nil), // 0: inboxapi.GetFeaturedProposalsResponse
	(*GetAISummaryRequest)(nil),          // 1: inboxapi.GetAISummaryRequest
	(*GetAISummaryResponse)(nil),         // 2: inboxapi.GetAISummaryResponse
	(*emptypb.Empty)(nil),                // 3: google.protobuf.Empty
}
var file_inboxapi_proposal_proto_depIdxs = []int32{
	3, // 0: inboxapi.Proposal.GetFeaturedProposals:input_type -> google.protobuf.Empty
	1, // 1: inboxapi.Proposal.GetAISummary:input_type -> inboxapi.GetAISummaryRequest
	0, // 2: inboxapi.Proposal.GetFeaturedProposals:output_type -> inboxapi.GetFeaturedProposalsResponse
	2, // 3: inboxapi.Proposal.GetAISummary:output_type -> inboxapi.GetAISummaryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inboxapi_proposal_proto_init() }
func file_inboxapi_proposal_proto_init() {
	if File_inboxapi_proposal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inboxapi_proposal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetFeaturedProposalsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_proposal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAISummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_proposal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAISummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inboxapi_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inboxapi_proposal_proto_goTypes,
		DependencyIndexes: file_inboxapi_proposal_proto_depIdxs,
		MessageInfos:      file_inboxapi_proposal_proto_msgTypes,
	}.Build()
	File_inboxapi_proposal_proto = out.File
	file_inboxapi_proposal_proto_rawDesc = nil
	file_inboxapi_proposal_proto_goTypes = nil
	file_inboxapi_proposal_proto_depIdxs = nil
}
