// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: inboxapi/settings.proto

package inboxapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPushTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token      string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeviceUuid string `protobuf:"bytes,3,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
}

func (x *AddPushTokenRequest) Reset() {
	*x = AddPushTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPushTokenRequest) ProtoMessage() {}

func (x *AddPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPushTokenRequest.ProtoReflect.Descriptor instead.
func (*AddPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{0}
}

func (x *AddPushTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddPushTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddPushTokenRequest) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

type RemovePushTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceUuid string `protobuf:"bytes,2,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
}

func (x *RemovePushTokenRequest) Reset() {
	*x = RemovePushTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePushTokenRequest) ProtoMessage() {}

func (x *RemovePushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePushTokenRequest.ProtoReflect.Descriptor instead.
func (*RemovePushTokenRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{1}
}

func (x *RemovePushTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemovePushTokenRequest) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

type PushTokenExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceUuid string `protobuf:"bytes,2,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
}

func (x *PushTokenExistsRequest) Reset() {
	*x = PushTokenExistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTokenExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenExistsRequest) ProtoMessage() {}

func (x *PushTokenExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenExistsRequest.ProtoReflect.Descriptor instead.
func (*PushTokenExistsRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{2}
}

func (x *PushTokenExistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushTokenExistsRequest) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

type PushTokenExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *PushTokenExistsResponse) Reset() {
	*x = PushTokenExistsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTokenExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenExistsResponse) ProtoMessage() {}

func (x *PushTokenExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenExistsResponse.ProtoReflect.Descriptor instead.
func (*PushTokenExistsResponse) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{3}
}

func (x *PushTokenExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type GetPushTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceUuid string `protobuf:"bytes,2,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
}

func (x *GetPushTokenRequest) Reset() {
	*x = GetPushTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushTokenRequest) ProtoMessage() {}

func (x *GetPushTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushTokenRequest.ProtoReflect.Descriptor instead.
func (*GetPushTokenRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{4}
}

func (x *GetPushTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPushTokenRequest) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

type PushTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PushTokenResponse) Reset() {
	*x = PushTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenResponse) ProtoMessage() {}

func (x *PushTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenResponse.ProtoReflect.Descriptor instead.
func (*PushTokenResponse) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{5}
}

func (x *PushTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPushTokenListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetPushTokenListRequest) Reset() {
	*x = GetPushTokenListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushTokenListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushTokenListRequest) ProtoMessage() {}

func (x *GetPushTokenListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushTokenListRequest.ProtoReflect.Descriptor instead.
func (*GetPushTokenListRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{6}
}

func (x *GetPushTokenListRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PushTokenDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceUuid string `protobuf:"bytes,2,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
}

func (x *PushTokenDetails) Reset() {
	*x = PushTokenDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTokenDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenDetails) ProtoMessage() {}

func (x *PushTokenDetails) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenDetails.ProtoReflect.Descriptor instead.
func (*PushTokenDetails) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{7}
}

func (x *PushTokenDetails) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PushTokenDetails) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

type PushTokenListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []*PushTokenDetails `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *PushTokenListResponse) Reset() {
	*x = PushTokenListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTokenListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTokenListResponse) ProtoMessage() {}

func (x *PushTokenListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTokenListResponse.ProtoReflect.Descriptor instead.
func (*PushTokenListResponse) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{8}
}

func (x *PushTokenListResponse) GetTokens() []*PushTokenDetails {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type PushSettingsDao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewProposalCreated *bool `protobuf:"varint,1,opt,name=new_proposal_created,json=newProposalCreated,proto3,oneof" json:"new_proposal_created,omitempty"`
	QuorumReached      *bool `protobuf:"varint,2,opt,name=quorum_reached,json=quorumReached,proto3,oneof" json:"quorum_reached,omitempty"`
	VoteFinishesSoon   *bool `protobuf:"varint,3,opt,name=vote_finishes_soon,json=voteFinishesSoon,proto3,oneof" json:"vote_finishes_soon,omitempty"`
	VoteFinished       *bool `protobuf:"varint,4,opt,name=vote_finished,json=voteFinished,proto3,oneof" json:"vote_finished,omitempty"`
}

func (x *PushSettingsDao) Reset() {
	*x = PushSettingsDao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushSettingsDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSettingsDao) ProtoMessage() {}

func (x *PushSettingsDao) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSettingsDao.ProtoReflect.Descriptor instead.
func (*PushSettingsDao) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{9}
}

func (x *PushSettingsDao) GetNewProposalCreated() bool {
	if x != nil && x.NewProposalCreated != nil {
		return *x.NewProposalCreated
	}
	return false
}

func (x *PushSettingsDao) GetQuorumReached() bool {
	if x != nil && x.QuorumReached != nil {
		return *x.QuorumReached
	}
	return false
}

func (x *PushSettingsDao) GetVoteFinishesSoon() bool {
	if x != nil && x.VoteFinishesSoon != nil {
		return *x.VoteFinishesSoon
	}
	return false
}

func (x *PushSettingsDao) GetVoteFinished() bool {
	if x != nil && x.VoteFinished != nil {
		return *x.VoteFinished
	}
	return false
}

type SetPushDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Dao    *PushSettingsDao `protobuf:"bytes,2,opt,name=dao,proto3" json:"dao,omitempty"`
}

func (x *SetPushDetailsRequest) Reset() {
	*x = SetPushDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPushDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPushDetailsRequest) ProtoMessage() {}

func (x *SetPushDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPushDetailsRequest.ProtoReflect.Descriptor instead.
func (*SetPushDetailsRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{10}
}

func (x *SetPushDetailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetPushDetailsRequest) GetDao() *PushSettingsDao {
	if x != nil {
		return x.Dao
	}
	return nil
}

type GetPushDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetPushDetailsRequest) Reset() {
	*x = GetPushDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushDetailsRequest) ProtoMessage() {}

func (x *GetPushDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetPushDetailsRequest) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{11}
}

func (x *GetPushDetailsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPushDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string           `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Dao    *PushSettingsDao `protobuf:"bytes,2,opt,name=dao,proto3" json:"dao,omitempty"`
}

func (x *GetPushDetailsResponse) Reset() {
	*x = GetPushDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inboxapi_settings_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPushDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPushDetailsResponse) ProtoMessage() {}

func (x *GetPushDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inboxapi_settings_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPushDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetPushDetailsResponse) Descriptor() ([]byte, []int) {
	return file_inboxapi_settings_proto_rawDescGZIP(), []int{12}
}

func (x *GetPushDetailsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPushDetailsResponse) GetDao() *PushSettingsDao {
	if x != nil {
		return x.Dao
	}
	return nil
}

var File_inboxapi_settings_proto protoreflect.FileDescriptor

var file_inboxapi_settings_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x69, 0x6e, 0x62, 0x6f, 0x78,
	0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x65, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x16, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x16, 0x50,
	0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22,
	0x31, 0x0a, 0x17, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x22, 0x4f, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55,
	0x75, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x11, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x32,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x49, 0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x22, 0x4b, 0x0a,
	0x15, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70,
	0x69, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0xa6, 0x02, 0x0a, 0x0f, 0x50,
	0x75, 0x73, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x44, 0x61, 0x6f, 0x12, 0x35,
	0x0a, 0x14, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x12,
	0x6e, 0x65, 0x77, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x5f,
	0x72, 0x65, 0x61, 0x63, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52,
	0x0d, 0x71, 0x75, 0x6f, 0x72, 0x75, 0x6d, 0x52, 0x65, 0x61, 0x63, 0x68, 0x65, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x31, 0x0a, 0x12, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x73, 0x5f, 0x73, 0x6f, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x02, 0x52,
	0x10, 0x76, 0x6f, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x73, 0x53, 0x6f, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x28, 0x0a, 0x0d, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6e,
	0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x03, 0x52, 0x0c, 0x76,
	0x6f, 0x74, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x88, 0x01, 0x01, 0x42, 0x17,
	0x0a, 0x15, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x5f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x71, 0x75, 0x6f, 0x72,
	0x75, 0x6d, 0x5f, 0x72, 0x65, 0x61, 0x63, 0x68, 0x65, 0x64, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x76,
	0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x73, 0x5f, 0x73, 0x6f, 0x6f,
	0x6e, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x65, 0x64, 0x22, 0x5d, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x03, 0x64, 0x61, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75,
	0x73, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x44, 0x61, 0x6f, 0x52, 0x03, 0x64,
	0x61, 0x6f, 0x22, 0x30, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x03, 0x64, 0x61, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x44, 0x61, 0x6f, 0x52,
	0x03, 0x64, 0x61, 0x6f, 0x32, 0xba, 0x04, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x45, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1d, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x2e, 0x69, 0x6e,
	0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x75, 0x73,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x56, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6e, 0x62,
	0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x2e,
	0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69,
	0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x2e,
	0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x49, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x12, 0x1f, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x53,
	0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x53, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x73, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1f,
	0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x73,
	0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75,
	0x73, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x69, 0x6e, 0x62, 0x6f, 0x78, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inboxapi_settings_proto_rawDescOnce sync.Once
	file_inboxapi_settings_proto_rawDescData = file_inboxapi_settings_proto_rawDesc
)

func file_inboxapi_settings_proto_rawDescGZIP() []byte {
	file_inboxapi_settings_proto_rawDescOnce.Do(func() {
		file_inboxapi_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_inboxapi_settings_proto_rawDescData)
	})
	return file_inboxapi_settings_proto_rawDescData
}

var file_inboxapi_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_inboxapi_settings_proto_goTypes = []any{
	(*AddPushTokenRequest)(nil),     // 0: inboxapi.AddPushTokenRequest
	(*RemovePushTokenRequest)(nil),  // 1: inboxapi.RemovePushTokenRequest
	(*PushTokenExistsRequest)(nil),  // 2: inboxapi.PushTokenExistsRequest
	(*PushTokenExistsResponse)(nil), // 3: inboxapi.PushTokenExistsResponse
	(*GetPushTokenRequest)(nil),     // 4: inboxapi.GetPushTokenRequest
	(*PushTokenResponse)(nil),       // 5: inboxapi.PushTokenResponse
	(*GetPushTokenListRequest)(nil), // 6: inboxapi.GetPushTokenListRequest
	(*PushTokenDetails)(nil),        // 7: inboxapi.PushTokenDetails
	(*PushTokenListResponse)(nil),   // 8: inboxapi.PushTokenListResponse
	(*PushSettingsDao)(nil),         // 9: inboxapi.PushSettingsDao
	(*SetPushDetailsRequest)(nil),   // 10: inboxapi.SetPushDetailsRequest
	(*GetPushDetailsRequest)(nil),   // 11: inboxapi.GetPushDetailsRequest
	(*GetPushDetailsResponse)(nil),  // 12: inboxapi.GetPushDetailsResponse
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_inboxapi_settings_proto_depIdxs = []int32{
	7,  // 0: inboxapi.PushTokenListResponse.tokens:type_name -> inboxapi.PushTokenDetails
	9,  // 1: inboxapi.SetPushDetailsRequest.dao:type_name -> inboxapi.PushSettingsDao
	9,  // 2: inboxapi.GetPushDetailsResponse.dao:type_name -> inboxapi.PushSettingsDao
	0,  // 3: inboxapi.Settings.AddPushToken:input_type -> inboxapi.AddPushTokenRequest
	1,  // 4: inboxapi.Settings.RemovePushToken:input_type -> inboxapi.RemovePushTokenRequest
	2,  // 5: inboxapi.Settings.PushTokenExists:input_type -> inboxapi.PushTokenExistsRequest
	4,  // 6: inboxapi.Settings.GetPushToken:input_type -> inboxapi.GetPushTokenRequest
	6,  // 7: inboxapi.Settings.GetPushTokenList:input_type -> inboxapi.GetPushTokenListRequest
	10, // 8: inboxapi.Settings.SetPushDetails:input_type -> inboxapi.SetPushDetailsRequest
	11, // 9: inboxapi.Settings.GetPushDetails:input_type -> inboxapi.GetPushDetailsRequest
	13, // 10: inboxapi.Settings.AddPushToken:output_type -> google.protobuf.Empty
	13, // 11: inboxapi.Settings.RemovePushToken:output_type -> google.protobuf.Empty
	3,  // 12: inboxapi.Settings.PushTokenExists:output_type -> inboxapi.PushTokenExistsResponse
	5,  // 13: inboxapi.Settings.GetPushToken:output_type -> inboxapi.PushTokenResponse
	8,  // 14: inboxapi.Settings.GetPushTokenList:output_type -> inboxapi.PushTokenListResponse
	13, // 15: inboxapi.Settings.SetPushDetails:output_type -> google.protobuf.Empty
	12, // 16: inboxapi.Settings.GetPushDetails:output_type -> inboxapi.GetPushDetailsResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_inboxapi_settings_proto_init() }
func file_inboxapi_settings_proto_init() {
	if File_inboxapi_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inboxapi_settings_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddPushTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RemovePushTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PushTokenExistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*PushTokenExistsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetPushTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*PushTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetPushTokenListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PushTokenDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PushTokenListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PushSettingsDao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*SetPushDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetPushDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inboxapi_settings_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetPushDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_inboxapi_settings_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inboxapi_settings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inboxapi_settings_proto_goTypes,
		DependencyIndexes: file_inboxapi_settings_proto_depIdxs,
		MessageInfos:      file_inboxapi_settings_proto_msgTypes,
	}.Build()
	File_inboxapi_settings_proto = out.File
	file_inboxapi_settings_proto_rawDesc = nil
	file_inboxapi_settings_proto_goTypes = nil
	file_inboxapi_settings_proto_depIdxs = nil
}
