// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: inboxapi/user.proto

package inboxapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	User_CreateSession_FullMethodName           = "/inboxapi.User/CreateSession"
	User_UseAuthNonce_FullMethodName            = "/inboxapi.User/UseAuthNonce"
	User_GetUserProfile_FullMethodName          = "/inboxapi.User/GetUserProfile"
	User_GetUser_FullMethodName                 = "/inboxapi.User/GetUser"
	User_GetSession_FullMethodName              = "/inboxapi.User/GetSession"
	User_DeleteSession_FullMethodName           = "/inboxapi.User/DeleteSession"
	User_DeleteUser_FullMethodName              = "/inboxapi.User/DeleteUser"
	User_AddView_FullMethodName                 = "/inboxapi.User/AddView"
	User_LastViewed_FullMethodName              = "/inboxapi.User/LastViewed"
	User_TrackActivity_FullMethodName           = "/inboxapi.User/TrackActivity"
	User_AllowSendingPush_FullMethodName        = "/inboxapi.User/AllowSendingPush"
	User_GetUserCanVoteProposals_FullMethodName = "/inboxapi.User/GetUserCanVoteProposals"
	User_GetAvailableDaoByWallet_FullMethodName = "/inboxapi.User/GetAvailableDaoByWallet"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	// Create new session for user with specific account info
	// if user doesn't exist, create new user
	// if user exists, create new session for user
	// returns new session info, user account info and last sessions
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	UseAuthNonce(ctx context.Context, in *UseAuthNonceRequest, opts ...grpc.CallOption) (*UseAuthNonceResponse, error)
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddView(ctx context.Context, in *UserViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	LastViewed(ctx context.Context, in *UserLastViewedRequest, opts ...grpc.CallOption) (*UserLastViewedResponse, error)
	TrackActivity(ctx context.Context, in *TrackActivityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AllowSendingPush(ctx context.Context, in *AllowSendingPushRequest, opts ...grpc.CallOption) (*AllowSendingPushResponse, error)
	GetUserCanVoteProposals(ctx context.Context, in *GetUserCanVoteProposalsRequest, opts ...grpc.CallOption) (*GetUserCanVoteProposalsResponse, error)
	GetAvailableDaoByWallet(ctx context.Context, in *GetAvailableDaoByWalletRequest, opts ...grpc.CallOption) (*GetAvailableDaoByWalletResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, User_CreateSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UseAuthNonce(ctx context.Context, in *UseAuthNonceRequest, opts ...grpc.CallOption) (*UseAuthNonceResponse, error) {
	out := new(UseAuthNonceResponse)
	err := c.cc.Invoke(ctx, User_UseAuthNonce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, User_GetUserProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, User_GetUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, User_GetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_DeleteSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_DeleteUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AddView(ctx context.Context, in *UserViewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_AddView_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LastViewed(ctx context.Context, in *UserLastViewedRequest, opts ...grpc.CallOption) (*UserLastViewedResponse, error) {
	out := new(UserLastViewedResponse)
	err := c.cc.Invoke(ctx, User_LastViewed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) TrackActivity(ctx context.Context, in *TrackActivityRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, User_TrackActivity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) AllowSendingPush(ctx context.Context, in *AllowSendingPushRequest, opts ...grpc.CallOption) (*AllowSendingPushResponse, error) {
	out := new(AllowSendingPushResponse)
	err := c.cc.Invoke(ctx, User_AllowSendingPush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserCanVoteProposals(ctx context.Context, in *GetUserCanVoteProposalsRequest, opts ...grpc.CallOption) (*GetUserCanVoteProposalsResponse, error) {
	out := new(GetUserCanVoteProposalsResponse)
	err := c.cc.Invoke(ctx, User_GetUserCanVoteProposals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetAvailableDaoByWallet(ctx context.Context, in *GetAvailableDaoByWalletRequest, opts ...grpc.CallOption) (*GetAvailableDaoByWalletResponse, error) {
	out := new(GetAvailableDaoByWalletResponse)
	err := c.cc.Invoke(ctx, User_GetAvailableDaoByWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	// Create new session for user with specific account info
	// if user doesn't exist, create new user
	// if user exists, create new session for user
	// returns new session info, user account info and last sessions
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	UseAuthNonce(context.Context, *UseAuthNonceRequest) (*UseAuthNonceResponse, error)
	GetUserProfile(context.Context, *GetUserProfileRequest) (*UserProfile, error)
	GetUser(context.Context, *GetUserRequest) (*UserInfo, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	AddView(context.Context, *UserViewRequest) (*emptypb.Empty, error)
	LastViewed(context.Context, *UserLastViewedRequest) (*UserLastViewedResponse, error)
	TrackActivity(context.Context, *TrackActivityRequest) (*emptypb.Empty, error)
	AllowSendingPush(context.Context, *AllowSendingPushRequest) (*AllowSendingPushResponse, error)
	GetUserCanVoteProposals(context.Context, *GetUserCanVoteProposalsRequest) (*GetUserCanVoteProposalsResponse, error)
	GetAvailableDaoByWallet(context.Context, *GetAvailableDaoByWalletRequest) (*GetAvailableDaoByWalletResponse, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedUserServer) UseAuthNonce(context.Context, *UseAuthNonceRequest) (*UseAuthNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseAuthNonce not implemented")
}
func (UnimplementedUserServer) GetUserProfile(context.Context, *GetUserProfileRequest) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedUserServer) GetUser(context.Context, *GetUserRequest) (*UserInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedUserServer) DeleteSession(context.Context, *DeleteSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedUserServer) DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserServer) AddView(context.Context, *UserViewRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddView not implemented")
}
func (UnimplementedUserServer) LastViewed(context.Context, *UserLastViewedRequest) (*UserLastViewedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LastViewed not implemented")
}
func (UnimplementedUserServer) TrackActivity(context.Context, *TrackActivityRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TrackActivity not implemented")
}
func (UnimplementedUserServer) AllowSendingPush(context.Context, *AllowSendingPushRequest) (*AllowSendingPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllowSendingPush not implemented")
}
func (UnimplementedUserServer) GetUserCanVoteProposals(context.Context, *GetUserCanVoteProposalsRequest) (*GetUserCanVoteProposalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCanVoteProposals not implemented")
}
func (UnimplementedUserServer) GetAvailableDaoByWallet(context.Context, *GetAvailableDaoByWalletRequest) (*GetAvailableDaoByWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableDaoByWallet not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UseAuthNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseAuthNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UseAuthNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UseAuthNonce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UseAuthNonce(ctx, req.(*UseAuthNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AddView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AddView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddView(ctx, req.(*UserViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LastViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLastViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LastViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_LastViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LastViewed(ctx, req.(*UserLastViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_TrackActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).TrackActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_TrackActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).TrackActivity(ctx, req.(*TrackActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_AllowSendingPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllowSendingPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AllowSendingPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_AllowSendingPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AllowSendingPush(ctx, req.(*AllowSendingPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserCanVoteProposals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCanVoteProposalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserCanVoteProposals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUserCanVoteProposals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserCanVoteProposals(ctx, req.(*GetUserCanVoteProposalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetAvailableDaoByWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableDaoByWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetAvailableDaoByWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetAvailableDaoByWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetAvailableDaoByWallet(ctx, req.(*GetAvailableDaoByWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inboxapi.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _User_CreateSession_Handler,
		},
		{
			MethodName: "UseAuthNonce",
			Handler:    _User_UseAuthNonce_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _User_GetUserProfile_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _User_GetUser_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _User_GetSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _User_DeleteSession_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _User_DeleteUser_Handler,
		},
		{
			MethodName: "AddView",
			Handler:    _User_AddView_Handler,
		},
		{
			MethodName: "LastViewed",
			Handler:    _User_LastViewed_Handler,
		},
		{
			MethodName: "TrackActivity",
			Handler:    _User_TrackActivity_Handler,
		},
		{
			MethodName: "AllowSendingPush",
			Handler:    _User_AllowSendingPush_Handler,
		},
		{
			MethodName: "GetUserCanVoteProposals",
			Handler:    _User_GetUserCanVoteProposals_Handler,
		},
		{
			MethodName: "GetAvailableDaoByWallet",
			Handler:    _User_GetAvailableDaoByWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inboxapi/user.proto",
}
